In [20]:
import pandas as pd

In [21]:
df= pd.read_csv("preprocessed_data.csv")

In [22]:
df= df.dropna()
df['topics']= df['topics'].str.split(',').str[0]

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

#define vectorizer parameters
tfidfconverter = TfidfVectorizer(max_features=1500, min_df=5, max_df=0.7)
tfidf_matrix = tfidfconverter.fit_transform(df["processed_text"]) #fit the vectorizer to synopses

print(tfidf_matrix.shape)

(48257, 1500)

In [24]:
terms = tfidfconverter.get_feature_names()

In [25]:
tfidf_matrix=tfidf_matrix.toarray()

In [26]:
from sklearn.cluster import KMeans

num_clusters = 5

km = KMeans(n_clusters=num_clusters)

km.fit(tfidf_matrix)

clusters = km.labels_.tolist()

In [27]:
clusters

[3,
 3,
 3,
 2,
 2,
 2,
 0,
 3,
 4,
 4,
 4,
 4,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 4,
 4,
 2,
 3,
 2,
 3,
 4,
 4,
 4,
 4,
 2,
 2,
 2,
 0,
 2,
 4,
 3,
 0,
 4,
 2,
 3,
 4,
 2,
 1,
 3,
 3,
 2,
 2,
 3,
 4,
 3,
 4,
 3,
 0,
 2,
 1,
 4,
 3,
 0,
 4,
 4,
 4,
 0,
 4,
 0,
 2,
 4,
 0,
 4,
 4,
 3,
 3,
 0,
 0,
 3,
 2,
 2,
 4,
 4,
 0,
 2,
 3,
 4,
 2,
 4,
 0,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 4,
 4,
 4,
 2,
 4,
 4,
 0,
 4,
 4,
 4,
 3,
 4,
 0,
 4,
 4,
 0,
 0,
 4,
 3,
 2,
 0,
 3,
 4,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 0,
 3,
 3,
 0,
 3,
 3,
 0,
 3,
 3,
 2,
 4,
 3,
 3,
 4,
 0,
 3,
 0,
 3,
 2,
 3,
 2,
 3,
 3,
 1,
 1,
 3,
 0,
 3,
 4,
 3,
 3,
 1,
 4,
 1,
 3,
 3,
 3,
 0,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 2,
 3,
 3,
 1,
 3,
 3,
 3,
 0,
 3,
 3,
 3,
 3,
 1,
 3,
 3,
 3,
 3,
 0,
 2,
 3,
 0,
 4,
 3,
 3,
 3,
 1,
 0,
 1,
 0,
 0,
 1,
 3,
 3,
 3,
 3,
 0,
 3,
 4,
 3,
 3,
 0,
 1,
 3,
 3,
 3,
 3,
 3,
 1,
 3,
 0,
 3,
 3,
 3,
 3,
 1,
 1,
 0,
 3,
 3,
 1,
 3,
 4,
 3,
 3,
 0,
 0,
 0,
 3,
 1,
 3,
 3,
 0,
 0,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 3,
 3,
 0,
 1,
 4,
 0,
 2,
 0,
 3,
 0,
 3,
 3,
 3,
 1,
 3,
 3,
 0,
 0,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 0,
 3,
 0,
 3,
 3,
 1,
 0,
 3,
 0,
 3,
 3,
 4,
 3,
 3,
 3,
 0,
 0,
 3,
 3,
 3,
 3,
 3,
 3,
 0,
 2,
 3,
 0,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 3,
 0,
 1,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 3,
 3,
 3,
 3,
 3,
 0,
 3,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 0,
 4,
 4,
 3,
 4,
 4,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 0,
 0,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 0,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 0,
 0,
 0,
 4,
 4,
 0,
 4,
 0,
 4,
 4,
 4,
 4,
 4,
 0,
 4,
 0,
 0,
 4,
 0,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 2,
 2,
 2,
 4,
 3,
 2,
 4,
 0,
 0,
 0,
 0,
 4,
 4,
 4,
 2,
 4,
 2,
 2,
 3,
 4,
 4,
 0,
 2,
 2,
 2,
 0,
 2,
 2,
 0,
 4,
 0,
 3,
 2,
 2,
 3,
 2,
 3,
 2,
 3,
 2,
 2,
 2,
 0,
 3,
 2,
 4,
 4,
 0,
 2,
 4,
 2,
 3,
 2,
 4,
 3,
 0,
 2,
 0,
 4,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 0,
 4,
 4,
 4,
 0,
 4,
 0,
 0,
 0,
 0,
 0,
 4,
 0,
 0,
 0,
 0,
 4,
 4,
 0,
 0,
 0,
 0,
 4,
 4,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 4,
 4,
 0,
 4,
 0,
 0,
 0,
 2,
 2,
 4,
 4,
 0,
 4,
 0,
 4,
 0,
 0,
 3,
 3,
 0,
 2,
 4,
 0,
 0,
 4,
 3,
 2,
 0,
 2,
 3,
 0,
 2,
 0,
 0,
 2,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 3,
 4,
 3,
 4,
 3,
 4,
 2,
 0,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 0,
 4,
 0,
 4,
 4,
 4,
 0,
 0,
 4,
 4,
 2,
 4,
 2,
 2,
 1,
 4,
 3,
 1,
 1,
 4,
 4,
 4,
 3,
 2,
 3,
 2,
 2,
 1,
 1,
 1,
 4,
 1,
 3,
 0,
 2,
 2,
 1,
 0,
 2,
 1,
 2,
 4,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 4,
 2,
 2,
 4,
 4,
 4,
 3,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 2,
 4,
 3,
 1,
 0,
 3,
 0,
 4,
 4,
 4,
 4,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 3,
 4,
 3,
 4,
 4,
 2,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 2,
 0,
 4,
 4,
 4,
 4,
 2,
 2,
 4,
 4,
 2,
 4,
 0,
 4,
 0,
 2,
 4,
 2,
 2,
 0,
 4,
 2,
 4,
 2,
 4,
 3,
 4,
 2,
 4,
 2,
 3,
 3,
 3,
 2,
 2,
 2,
 4,
 4,
 4,
 4,
 2,
 3,
 0,
 2,
 0,
 4,
 4,
 2,
 2,
 2,
 2,
 2,
 4,
 2,
 3,
 2,
 3,
 4,
 4,
 4,
 2,
 4,
 2,
 0,
 4,
 0,
 4,
 4,
 4,
 0,
 4,
 0,
 2,
 4,
 4,
 2,
 2,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 4,
 3,
 4,
 3,
 3,
 4,
 3,
 0,
 3,
 3,
 4,
 4,
 4,
 0,
 3,
 2,
 2,
 2,
 4,
 2,
 2,
 2,
 4,
 0,
 2,
 2,
 4,
 0,
 4,
 4,
 1,
 4,
 2,
 2,
 3,
 0,
 0,
 4,
 2,
 3,
 2,
 0,
 3,
 0,
 0,
 2,
 2,
 4,
 2,
 4,
 2,
 0,
 2,
 0,
 0,
 3,
 3,
 2,
 2,
 4,
 2,
 3,
 3,
 4,
 4,
 2,
 4,
 2,
 4,
 4,
 4,
 2,
 3,
 4,
 1,
 0,
 2,
 4,
 2,
 4,
 4,
 2,
 2,
 0,
 2,
 1,
 4,
 0,
 4,
 4,
 3,
 4,
 4,
 0,
 4,
 3,
 2,
 4,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 3,
 4,
 3,
 4,
 0,
 4,
 3,
 4,
 3,
 1,
 4,
 4,
 3,
 3,
 4,
 0,
 0,
 3,
 2,
 0,
 0,
 0,
 0,
 3,
 2,
 4,
 0,
 0,
 0,
 1,
 0,
 3,
 0,
 3,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 4,
 4,
 4,
 3,
 4,
 4,
 4,
 4,
 4,
 3,
 4,
 3,
 3,
 2,
 4,
 2,
 4,
 4,
 4,
 4,
 0,
 2,
 4,
 2,
 ...]

In [28]:
df['clusters']=clusters
df['clusters'].value_counts()

4    15735
3    12211
0     9636
2     7475
1     3200
Name: clusters, dtype: int64

In [29]:
grouped = df.groupby(df['clusters'])

In [30]:
print(grouped.mean())

                 itemid  clusters
clusters
0         453062.693753       0.0
1         454871.771875       1.0
2         453538.038930       2.0
3         453253.391614       3.0
4         453776.153352       4.0

In [31]:
for i in grouped:
    print(i)

(0,                                                 headline  itemid  \
6        FOCUS - Coffee drops after a spectacular rally.  326920
12     Indian Shipping -- Visakhapatnam Cargoes - Mar...  368473
14           Indian chemicals prices - Delhi - March 13.  368475
15        Indian oils & oilseeds  prices-Delhi-March 13.  368476
16         Indian gur & sugar prices - Delhi - March 13.  368477
17          Indian foodgrains prices - Delhi - March 13.  368478
18               INDIA GOVERNMENT SECURITIES - March 13.  368479
19        Forthcoming book-closures of Indian companies.  368480
20       Forthcoming board meetings of Indian companies.  368481
21       INDICATORS - Key Indian economic data-March 13.  368482
35                     Delta drops cargo fuel surcharge.  377577
39      Union Miniere sees $1,200 avge world zinc price.  377581
55      Specialists get 100 bln lire of Italy 30-yr BTP.  393143
60     Italian refinery runs fall 1.7 pct in Jan - tr...  393148
64      Specialists get 150 bln lire of Italy 10-yr BTP.  393152
66       EU maintains flour export refund at eight Ecus.  393154
69     EU sets 15 Ecu rebate for maize export to E.Eu...  393157
74     Specialists allocated 200 bln lire of Italy CCTs.  393162
75     Italy's oil consumption falls 8.7 pct in Feb -...  393163
81     ARA bunkers head higher but buyers still reluc...  393169
87        Portugal Feb inflation to be published Friday.  406187
105     EU sets refund for maize exports to Switzerland.  406205
111    OFFICIAL JOURNAL CONTENTS - OJ L 66 OF MARCH 6...  429411
114    OFFICIAL JOURNAL CONTENTS - OJ L 68 OF MARCH 8...  429414
115    Canada provincial T-bill auction results - Man...  429415
119          Imperial Oil cuts Canada posted oil prices.  429419
131             Atlantic Coast Feb load factor 38.2 pct.  429431
134           U.S. corporate bonds - new issue pricings.  429434
137                     Reuter Commodity Index - Mar 10.  429437
145    U.S. spot resid prices hold despite crude sell...  429445
...                                                  ...     ...
48211  Bridgestone said seeking offers, rubber trade ...  477722
48212     Singapore hikes petrol and diesel pump prices.  477723
48214  Asia Product Swaps - Gas oil drifts in quiet t...  477725
48215   Bangchak awards one MidEast crude, but not Oman.  477726
48219             KL tin down two cents at 14.27 rgt/kg.  477730
48227  Rubber-Thais creating two-tier market, trade q...  477738
48232   Itochu to step up gasoline sales under own name.  477743
48233         Shanghai Metal Exchange warehouse figures.  477744
48236          Petronas Gas Islamic bonds rated P1 -RAM.  477747
48239   Thailand aims to boost commodity sales to China.  477750
48241      Rubber - prices seen easier on rising stocks.  477752
48243  Taiwan tenders to buy May jet fuel, closes Apr 1.  477754
48256     Taiwan buys May fuel oil at $123/T and $131/T.  477767
48263  Philippine mills buy 100,000 tonnes Canadian w...  477774
48267   Philippine mills buy 100,000 tns Canadian wheat.  477778
48281        Philippines says to buy 40,000 tonnes corn.  477792
48287  Japan MOF to hold 4-year note auction on Tuesday.  477798
48288   Japan Feb lead battery sales fall 3.0 pct yr/yr.  477799
48290  Manila buys 1.63 mln bags of sugar to prop pri...  477801
48294  PH-ADR Philippine stocks traded abroad. [CORRE...  477805
48301  S.Korean firms buy 49,150 tonnes of Thai tapioca.  477812
48312  Port conditions update - Algeria - Lloyds Ship...  477823
48327   Bahrain says 48.2 mln dinar trade surplus in Q4.  477838
48331     Adgas in LNG supply talks to Korea Gas - MEES.  477842
48332   Saudi petchem delays support LPG exports - MEES.  477843
48341  Egypt offers 91-day T-bills worth 600 mln pounds.  477852
48342     Lebanese markets and financial markets closed.  477853
48350      Greek 1M ATHIBOR rose to 10.90 from 10.72pct.  477861
48351  Greek 1M ATHIBOR edges up to 10.72 from 10.72pct.  477862
48364  India retains import curbs on consumer electro...  477875

                                                    text datepublished topics  \
6      world coffee markets have had a tumble after a...    1997-03-18    M14
12     following is the berthing schedule of major ve...    1997-03-13    M14
14     rates supplied by asian news international, ne...    1997-03-13    M14
15     rates supplied by asian news international, ne...    1997-03-13    M14
16     rates supplied by asian news international, ne...    1997-03-13    M14
17     rates supplied by asian news international, ne...    1997-03-13    M14
18     government\tindicative    coupon\t  yield to  ...    1997-03-13    M12
19     ----------------------------------------------...    1997-03-13    C15
20     company\t\t   date of meeting\tpurpose -------...    1997-03-13    C15
21     *********** daily indicators *********** \t\t\...    1997-03-13    E71
35     delta air lines said it will drop its 10 us ce...    1997-03-13    C31
39     belgian non-ferrous metals company union minie...    1997-03-13    C31
55     specialist bond traders were allocated 100 bil...    1997-03-13    M12
60     italian refinery runs fell 1.7 percent in janu...    1997-03-13    C21
64     specialist bond traders were allocated 150 bil...    1997-03-13    M12
66     the european union on thursday kept the main w...    1997-03-13    M14
69     the european union on thursday set a special r...    1997-03-13    M14
74     specialist bond traders were allocated 200 bil...    1997-03-13    M12
75     italian consumption of petroleum products fell...    1997-03-13    C21
81     rotterdam bunker prices edged higher on thursd...    1997-03-13    M14
87     portugal's national statistics institute (ine)...    1997-03-13    E13
105    the european union on thursday set a daily exp...    1997-03-13    M14
111    * council regulation (ec) no 390/97 of 20 dece...    1997-03-10    G15
114    * (note - contents are displayed in reverse or...    1997-03-10    G15
115    date  prov   mat    c$amt   avg   chg  price  ...    1997-03-10    M13
119    imperial oil ltd said it lowered the price it ...    1997-03-10    M14
131    1997\t\t  1996  load factor - percent\t\t  38....    1997-03-10    C31
134    date   issuer\tamt  term  coupon  price   yiel...    1997-03-10    M12
137    today  prev  four wks ago  yr ago \t\t\t 2003....    1997-03-10    M14
145    u.s. spot residual fuel prices mostly held ste...    1997-03-10    M14
...                                                  ...           ...    ...
48211  bridgestone is said to be asking for offers in...    1997-03-31    M14
48212  singapore petrol and diesel pump prices rose o...    1997-03-31    C31
48214  singapore gas oil swaps drifted sideways in qu...    1997-03-31    M14
48215  bangchak petroleum plc awarded just one middle...    1997-03-31    C33
48219  malaysia's tin price fell two cents to 14.27 r...    1997-03-31    M14
48227  thailand may be digging itself a hole by engag...    1997-03-31    M14
48232  itochu corp said on monday it plans to step up...    1997-03-31    C11
48233  latest shanghai metal exchange stock figures a...    1997-03-31    M14
48236  rating agency malaysia (ram) announced on mond...    1997-03-31    C17
48239  thailand will secure deals to sell more rice, ...    1997-03-31    E51
48241  japanese rubber futures are likely to tread ea...    1997-03-31    M14
48243  taiwan's state-owned chinese petroleum corp (c...    1997-03-31    M14
48256  taiwan's state-owned chinese petroleum corp (c...    1997-03-31    M14
48263  two philippine mills bought 100,000 tonnes of ...    1997-03-31    M14
48267  two philippine mills bought 100,000 tonnes of ...    1997-03-31    M14
48281  the philippines' national food authority said ...    1997-03-31    M14
48287  the ministry of finance (mof) will hold a four...    1997-03-31    E21
48288  japan's sales of domestic lead batteries, meas...    1997-03-31    C31
48290  the national food authority said on monday it ...    1997-03-31    M14
48294  closing prices of philippine stocks traded on ...    1997-03-31    C15
48301  a south korean feed grain buyer group, known a...    1997-03-31    M14
48312  port conditions from lloyds shipping intellige...    1997-03-31    C24
48327  bahrain posted a 48.2 million dinar trade surp...    1997-03-31    E51
48331  abu dhabi gas liquefaction co (adgas) is in ta...    1997-03-31    C33
48332  saudi aramco's liquefied petroleum gas (lpg) e...    1997-03-31    C31
48341  the egyptian treasury offered 91-day treasury ...    1997-03-31    M13
48342  financial markets and exchanges in lebanon wer...    1997-03-31    M11
48350  the athens interbank offered rate (athibor) fo...    1997-03-31    M12
48351  the athens interbank offered rate (athibor) fo...    1997-03-31    M12
48364  india's commerce ministry, said on monday that...    1997-03-31   E512

        XMLfilename                                     processed_text  \
6      326920newsML  world coffee market tumble spectacular rally t...
12     368473newsML  following berthing schedule major vessel loadi...
14     368475newsML  rate supplied asian news international new del...
15     368476newsML  rate supplied asian news international new del...
16     368477newsML  rate supplied asian news international new del...
17     368478newsML  rate supplied asian news international new del...
18     368479newsML  government indicative coupon yield year securi...
19     368480newsML  ace laboratory march 27 15 dividend aps star i...
20     368481newsML  company date meeting purpose shaw wallace marc...
21     368482newsML  daily indicator wednesday previous rbi referen...
35     377577newsML  delta air line said drop 10 u cent per kg carg...
39     377581newsML  belgian metal company union miniere said thurs...
55     393143newsML  specialist bond trader allocated 100 billion l...
60     393148newsML  italian refinery run fell percent january vers...
64     393152newsML  specialist bond trader allocated 150 billion l...
66     393154newsML  european union thursday kept main wheat flour ...
69     393157newsML  european union thursday set special rebate 15 ...
74     393162newsML  specialist bond trader allocated 200 billion l...
75     393163newsML  italian consumption petroleum product fell per...
81     393169newsML  rotterdam bunker price edged higher thursday f...
87     406187newsML  portugal national statistic institute ine expe...
105    406205newsML  european union thursday set daily export refun...
111    429411newsML  council regulation ec 20 december 1996 fixing ...
114    429414newsML  note content displayed reverse order printed j...
115    429415newsML  date prov mat c amt avg chg price hi lo man 25...
119    429419newsML  imperial oil ltd said lowered price would pay ...
131    429431newsML  1997 1996 load factor percent revenue passenge...
134    429434newsML  date issuer amt term coupon price yield sprd m...
137    429437newsML  today prev four wks ago yr ago mar 10 mar 07 f...
145    429445newsML  spot residual fuel price mostly held steady mo...
...             ...                                                ...
48211  477722newsML  bridgestone said asking offer market sir20 rub...
48212  477723newsML  singapore petrol diesel pump price rose weeken...
48214  477725newsML  singapore gas oil swap drifted sideways quiet ...
48215  477726newsML  bangchak petroleum plc awarded one middle east...
48219  477730newsML  malaysia tin price fell two cent ringgit kg se...
48227  477738newsML  thailand may digging hole engaging rubber buyi...
48232  477743newsML  itochu corp said monday plan step gasoline sal...
48233  477744newsML  latest shanghai metal exchange stock figure to...
48236  477747newsML  rating agency malaysia ram announced monday ha...
48239  477750newsML  thailand secure deal sell rice rubber tapioca ...
48241  477752newsML  japanese rubber future likely tread easier wee...
48243  477754newsML  taiwan chinese petroleum corp cpc ha issued te...
48256  477767newsML  taiwan chinese petroleum corp cpc ha bought te...
48263  477774newsML  two philippine mill bought tonne canadian whea...
48267  477778newsML  two philippine mill bought tonne canadian whea...
48281  477792newsML  philippine national food authority said monday...
48287  477798newsML  ministry finance mof hold government note auct...
48288  477799newsML  japan sale domestic lead battery measured volu...
48290  477801newsML  national food authority said monday far bought...
48294  477805newsML  closing price philippine stock traded wall str...
48301  477812newsML  south korean feed grain buyer group known feed...
48312  477823newsML  port condition lloyd shipping intelligence ser...
48327  477838newsML  bahrain posted million dinar trade surplus fou...
48331  477842newsML  abu dhabi gas liquefaction co adgas talk korea...
48332  477843newsML  saudi aramco liquefied petroleum gas lpg expor...
48341  477852newsML  egyptian treasury offered treasury bill worth ...
48342  477853newsML  financial market exchange lebanon closed monda...
48350  477861newsML  athens interbank offered rate athibor one mont...
48351  477862newsML  athens interbank offered rate athibor one mont...
48364  477875newsML  india commerce ministry said monday export pro...

       clusters
6             0
12            0
14            0
15            0
16            0
17            0
18            0
19            0
20            0
21            0
35            0
39            0
55            0
60            0
64            0
66            0
69            0
74            0
75            0
81            0
87            0
105           0
111           0
114           0
115           0
119           0
131           0
134           0
137           0
145           0
...         ...
48211         0
48212         0
48214         0
48215         0
48219         0
48227         0
48232         0
48233         0
48236         0
48239         0
48241         0
48243         0
48256         0
48263         0
48267         0
48281         0
48287         0
48288         0
48290         0
48294         0
48301         0
48312         0
48327         0
48331         0
48332         0
48341         0
48342         0
48350         0
48351         0
48364         0

[9636 rows x 8 columns])
(1,                                                 headline  itemid  \
45         Spain's Pryca to pay dividend, issue premium.  377587
57            Sibeka swings to 1996 loss of 125 mln Bfr.  393145
154                  Datapoint Q2 Jan 25 profit vs loss.  429454
155            John Alden Financial Q4 net loss narrows.  429455
162                        Aydin Corp Q4 loss vs profit.  429462
164             Air & Water Q1 shr loss widens to $0.42.  429464
176                Biosite Diagnostics Inc Q4 shr falls.  429476
180                      Newpark Resources Q4 net rises.  429480
189                      Elbit Ltd Q4 net loss narrowed.  429489
202           Grill Concepts Q4 shr loss with writedown.  429502
204                 American Financial Q4 oper shr down.  429504
207              Phillips-Van Heusen Q4 Feb 2 net rises.  429507
218           Great Atlantic & Pacific Tea Q4 shr $0.60.  429518
224          Graham-Field Health Q4 shr oper loss $0.92.  429524
231               Atrix Laboratories Q4 net loss widens.  429531
232            Greif Bros Q1 class A shr $0.14 vs $0.41.  429532
236                   Video Update Inc Q3 Jan 31 net up.  429536
245            ABM Industries Inc Q1 shr rises to $0.22.  429545
260                  Charter Power Systems Q4 shr rises.  429560
270               Craig preliminary 1996 oper shr $0.02.  429570
288           Resurgence Properties Inc Q4 full results.  429588
323          National Beverage Corp Q3 Jan 25 net rises.  429623
326                          Marina LP Q4 net decreases.  429626
340                    Del Global Q2 Feb 1 full results.  429640
640                Berzacks-Illman ups interim shr, div.  429940
643           Berzacks lifts interim shr, div increased.  429943
644                      Voltex raises interim shr, div.  429944
653          Batecor half year loss narrows, scraps div.  429953
654              EL Bateman half yr headline shr surges.  429954
655              Ceramic Industries interim shr, div up.  429955
...                                                  ...     ...
47897                Israel's IDB Holding 1996 net down.  477408
47898              IDB Development 1996 net profit down.  477409
47899   Saudi Ceramics Co 1996 net profit drops sharply.  477410
47900          Saudi Public Transport Co lifts 1996 net.  477411
47922  Saudi's Ahsa Development Co 1996 net profit fa...  477433
47928                       Bank Leumi Q4 net profit up.  477439
48001            Littlefield, Adams Q4 shr loss narrows.  477512
48145       Nippon Sheet Glass French affiliate to shut.  477656
48150                       Aisin -96/97 group forecast.  477661
48152                      Aisin -96/97 parent forecast.  477663
48158         Mitsubishi Electric -96/97 group forecast.  477669
48160        Mitsubishi Electric -96/97 parent forecast.  477671
48179                 Pigeon Corp -97/98 group forecast.  477690
48180                 Pigeon Corp - 96/97 group results.  477691
48181               Kabuto Decom -96/97 parent forecast.  477692
48182              Taiko Electric -96/97 group forecast.  477693
48183                Nihon Seiko -96/97 parent forecast.  477694
48184             Taiko Electric -96/97 parent forecast.  477695
48185                 Unisia Jecs -96/97 group forecast.  477696
48186                Unisia Jecs -96/97 parent forecast.  477697
48234         Pan Malayan 1996 net S$3.8 mln, up 13 pct.  477745
48250       TIBS Holdings 1996 net plunges into the red.  477761
48271                       Gudang Garam 1996 net soars.  477782
48276              Tat Lee Finance 1996 net up 19.6 pct.  477787
48277          Indocement says 96 net at 551.49 bln rph.  477788
48280                    Gajah Tunggal says 1996 net up.  477791
48286          Tat Lee 1996 net up 13 pct to S$68.9 mln.  477797
48323         Kuwait's al-Ahli Bank says net up 45.9pct.  477834
48337               Israel's Elco Q4 net loss vs profit.  477848
48343          Israel's Mizrahi Bank 1996 net profit up.  477854

                                                    text datepublished topics  \
45     spain's hypermarket chain pryca said on thursd...    1997-03-13    C15
57     year to december 31, 1996 (in millions of belg...    1997-03-13    C15
154    (in thousands, except per share data) \t\t\t  ...    1997-03-10    C15
155    1996\t\t\t1995  shr loss\t  $0.10\t loss     $...    1997-03-10    C15
162    1996\t\t\t1995  shr  loss\t\t  $0.63   profit\...    1997-03-10    C15
164    1996\t\t\t1995  shr loss\t  $0.42\t     loss $...    1997-03-10    C15
176    biosite diagnostics inc. \t\t\t\tstatement of ...    1997-03-10    C15
180    (in 000's except per share amounts) \t\t\t\t\t...    1997-03-10    C15
189    for the year ended  for the three months \t\t\...    1997-03-10    C15
202    grill concepts, inc. and subsidiaries \t\t\t  ...    1997-03-10    C15
204    three months ended\tyear ended \t\t\t\t     de...    1997-03-10    C15
207    1997\t\t\t1996  shr\t\t\t  $0.29\t\t    $0.15 ...    1997-03-10    C15
218    (in thousands, except share amounts and store ...    1997-03-10    C15
224    graham-field health products inc and subsidiar...    1997-03-10    C15
231    three months ended\t year ended \t\t\t    dece...    1997-03-10    C15
232    three mos ended\t   three mos ended \t\t\t\t j...    1997-03-10    C15
236    (in thousands, except per share amounts) \t\t\...    1997-03-10    C15
245    abm industries inc. \t\t\t\t\t\t  (unaudited) ...    1997-03-10    C15
260    charter power systems, inc. and subsidiaries \...    1997-03-10    C15
270    craig consumer electronics inc said monday tha...    1997-03-10    C15

In [32]:
datasets = {}
for groups, data in grouped:
        datasets[groups] = data

In [33]:
datasets[0]

,headline,itemid,text,datepublished,topics,XMLfilename,processed_text,clusters
6,FOCUS - Coffee drops after a spectacular rally.,326920,world coffee markets have had a tumble after a...,1997-03-18,M14,326920newsML,world coffee market tumble spectacular rally t...,0
12,Indian Shipping -- Visakhapatnam Cargoes - Mar...,368473,following is the berthing schedule of major ve...,1997-03-13,M14,368473newsML,following berthing schedule major vessel loadi...,0
14,Indian chemicals prices - Delhi - March 13.,368475,"rates supplied by asian news international, ne...",1997-03-13,M14,368475newsML,rate supplied asian news international new del...,0
15,Indian oils & oilseeds prices-Delhi-March 13.,368476,"rates supplied by asian news international, ne...",1997-03-13,M14,368476newsML,rate supplied asian news international new del...,0
16,Indian gur & sugar prices - Delhi - March 13.,368477,"rates supplied by asian news international, ne...",1997-03-13,M14,368477newsML,rate supplied asian news international new del...,0
17,Indian foodgrains prices - Delhi - March 13.,368478,"rates supplied by asian news international, ne...",1997-03-13,M14,368478newsML,rate supplied asian news international new del...,0
18,INDIA GOVERNMENT SECURITIES - March 13.,368479,government\tindicative coupon\t yield to ...,1997-03-13,M12,368479newsML,government indicative coupon yield year securi...,0
19,Forthcoming book-closures of Indian companies.,368480,----------------------------------------------...,1997-03-13,C15,368480newsML,ace laboratory march 27 15 dividend aps star i...,0
20,Forthcoming board meetings of Indian companies.,368481,company\t\t date of meeting\tpurpose -------...,1997-03-13,C15,368481newsML,company date meeting purpose shaw wallace marc...,0
21,INDICATORS - Key Indian economic data-March 13.,368482,*********** daily indicators *********** \t\t\...,1997-03-13,E71,368482newsML,daily indicator wednesday previous rbi referen...,0
35,Delta drops cargo fuel surcharge.,377577,delta air lines said it will drop its 10 us ce...,1997-03-13,C31,377577newsML,delta air line said drop 10 u cent per kg carg...,0
39,"Union Miniere sees $1,200 avge world zinc price.",377581,belgian non-ferrous metals company union minie...,1997-03-13,C31,377581newsML,belgian metal company union miniere said thurs...,0
55,Specialists get 100 bln lire of Italy 30-yr BTP.,393143,specialist bond traders were allocated 100 bil...,1997-03-13,M12,393143newsML,specialist bond trader allocated 100 billion l...,0
60,Italian refinery runs fall 1.7 pct in Jan - tr...,393148,italian refinery runs fell 1.7 percent in janu...,1997-03-13,C21,393148newsML,italian refinery run fell percent january vers...,0
64,Specialists get 150 bln lire of Italy 10-yr BTP.,393152,specialist bond traders were allocated 150 bil...,1997-03-13,M12,393152newsML,specialist bond trader allocated 150 billion l...,0
66,EU maintains flour export refund at eight Ecus.,393154,the european union on thursday kept the main w...,1997-03-13,M14,393154newsML,european union thursday kept main wheat flour ...,0
69,EU sets 15 Ecu rebate for maize export to E.Eu...,393157,the european union on thursday set a special r...,1997-03-13,M14,393157newsML,european union thursday set special rebate 15 ...,0
74,Specialists allocated 200 bln lire of Italy CCTs.,393162,specialist bond traders were allocated 200 bil...,1997-03-13,M12,393162newsML,specialist bond trader allocated 200 billion l...,0
75,Italy's oil consumption falls 8.7 pct in Feb -...,393163,italian consumption of petroleum products fell...,1997-03-13,C21,393163newsML,italian consumption petroleum product fell per...,0
81,ARA bunkers head higher but buyers still reluc...,393169,rotterdam bunker prices edged higher on thursd...,1997-03-13,M14,393169newsML,rotterdam bunker price edged higher thursday f...,0
87,Portugal Feb inflation to be published Friday.,406187,portugal's national statistics institute (ine)...,1997-03-13,E13,406187newsML,portugal national statistic institute ine expe...,0
105,EU sets refund for maize exports to Switzerland.,406205,the european union on thursday set a daily exp...,1997-03-13,M14,406205newsML,european union thursday set daily export refun...,0
111,OFFICIAL JOURNAL CONTENTS - OJ L 66 OF MARCH 6...,429411,* council regulation (ec) no 390/97 of 20 dece...,1997-03-10,G15,429411newsML,council regulation ec 20 december 1996 fixing ...,0
114,OFFICIAL JOURNAL CONTENTS - OJ L 68 OF MARCH 8...,429414,* (note - contents are displayed in reverse or...,1997-03-10,G15,429414newsML,note content displayed reverse order printed j...,0
115,Canada provincial T-bill auction results - Man...,429415,date prov mat c$amt avg chg price ...,1997-03-10,M13,429415newsML,date prov mat c amt avg chg price hi lo man 25...,0
119,Imperial Oil cuts Canada posted oil prices.,429419,imperial oil ltd said it lowered the price it ...,1997-03-10,M14,429419newsML,imperial oil ltd said lowered price would pay ...,0
131,Atlantic Coast Feb load factor 38.2 pct.,429431,1997\t\t 1996 load factor - percent\t\t 38....,1997-03-10,C31,429431newsML,1997 1996 load factor percent revenue passenge...,0
134,U.S. corporate bonds - new issue pricings.,429434,date issuer\tamt term coupon price yiel...,1997-03-10,M12,429434newsML,date issuer amt term coupon price yield sprd m...,0
137,Reuter Commodity Index - Mar 10.,429437,today prev four wks ago yr ago \t\t\t 2003....,1997-03-10,M14,429437newsML,today prev four wks ago yr ago mar 10 mar 07 f...,0
145,U.S. spot resid prices hold despite crude sell...,429445,u.s. spot residual fuel prices mostly held ste...,1997-03-10,M14,429445newsML,spot residual fuel price mostly held steady mo...,0
...,...,...,...,...,...,...,...,...
48211,"Bridgestone said seeking offers, rubber trade ...",477722,bridgestone is said to be asking for offers in...,1997-03-31,M14,477722newsML,bridgestone said asking offer market sir20 rub...,0
48212,Singapore hikes petrol and diesel pump prices.,477723,singapore petrol and diesel pump prices rose o...,1997-03-31,C31,477723newsML,singapore petrol diesel pump price rose weeken...,0
48214,Asia Product Swaps - Gas oil drifts in quiet t...,477725,singapore gas oil swaps drifted sideways in qu...,1997-03-31,M14,477725newsML,singapore gas oil swap drifted sideways quiet ...,0
48215,"Bangchak awards one MidEast crude, but not Oman.",477726,bangchak petroleum plc awarded just one middle...,1997-03-31,C33,477726newsML,bangchak petroleum plc awarded one middle east...,0
48219,KL tin down two cents at 14.27 rgt/kg.,477730,malaysia's tin price fell two cents to 14.27 r...,1997-03-31,M14,477730newsML,malaysia tin price fell two cent ringgit kg se...,0
48227,"Rubber-Thais creating two-tier market, trade q...",477738,thailand may be digging itself a hole by engag...,1997-03-31,M14,477738newsML,thailand may digging hole engaging rubber buyi...,0
48232,Itochu to step up gasoline sales under own name.,477743,itochu corp said on monday it plans to step up...,1997-03-31,C11,477743newsML,itochu corp said monday plan step gasoline sal...,0
48233,Shanghai Metal Exchange warehouse figures.,477744,latest shanghai metal exchange stock figures a...,1997-03-31,M14,477744newsML,latest shanghai metal exchange stock figure to...,0
48236,Petronas Gas Islamic bonds rated P1 -RAM.,477747,rating agency malaysia (ram) announced on mond...,1997-03-31,C17,477747newsML,rating agency malaysia ram announced monday ha...,0
48239,Thailand aims to boost commodity sales to China.,477750,"thailand will secure deals to sell more rice, ...",1997-03-31,E51,477750newsML,thailand secure deal sell rice rubber tapioca ...,0
48241,Rubber - prices seen easier on rising stocks.,477752,japanese rubber futures are likely to tread ea...,1997-03-31,M14,477752newsML,japanese rubber future likely tread easier wee...,0
48243,"Taiwan tenders to buy May jet fuel, closes Apr 1.",477754,taiwan's state-owned chinese petroleum corp (c...,1997-03-31,M14,477754newsML,taiwan chinese petroleum corp cpc ha issued te...,0
48256,Taiwan buys May fuel oil at $123/T and $131/T.,477767,taiwan's state-owned chinese petroleum corp (c...,1997-03-31,M14,477767newsML,taiwan chinese petroleum corp cpc ha bought te...,0
48263,"Philippine mills buy 100,000 tonnes Canadian w...",477774,"two philippine mills bought 100,000 tonnes of ...",1997-03-31,M14,477774newsML,two philippine mill bought tonne canadian whea...,0
48267,"Philippine mills buy 100,000 tns Canadian wheat.",477778,"two philippine mills bought 100,000 tonnes of ...",1997-03-31,M14,477778newsML,two philippine mill bought tonne canadian whea...,0
48281,"Philippines says to buy 40,000 tonnes corn.",477792,the philippines' national food authority said ...,1997-03-31,M14,477792newsML,philippine national food authority said monday...,0
48287,Japan MOF to hold 4-year note auction on Tuesday.,477798,the ministry of finance (mof) will hold a four...,1997-03-31,E21,477798newsML,ministry finance mof hold government note auct...,0
48288,Japan Feb lead battery sales fall 3.0 pct yr/yr.,477799,"japan's sales of domestic lead batteries, meas...",1997-03-31,C31,477799newsML,japan sale domestic lead battery measured volu...,0
48290,Manila buys 1.63 mln bags of sugar to prop pri...,477801,the national food authority said on monday it ...,1997-03-31,M14,477801newsML,national food authority said monday far bought...,0
48294,PH-ADR Philippine stocks traded abroad. [CORRE...,477805,closing prices of philippine stocks traded on ...,1997-03-31,C15,477805newsML,closing price philippine stock traded wall str...,0
48301,"S.Korean firms buy 49,150 tonnes of Thai tapioca.",477812,"a south korean feed grain buyer group, known a...",1997-03-31,M14,477812newsML,south korean feed grain buyer group known feed...,0
48312,Port conditions update - Algeria - Lloyds Ship...,477823,port conditions from lloyds shipping intellige...,1997-03-31,C24,477823newsML,port condition lloyd shipping intelligence ser...,0
48327,Bahrain says 48.2 mln dinar trade surplus in Q4.,477838,bahrain posted a 48.2 million dinar trade surp...,1997-03-31,E51,477838newsML,bahrain posted million dinar trade surplus fou...,0
48331,Adgas in LNG supply talks to Korea Gas - MEES.,477842,abu dhabi gas liquefaction co (adgas) is in ta...,1997-03-31,C33,477842newsML,abu dhabi gas liquefaction co adgas talk korea...,0
48332,Saudi petchem delays support LPG exports - MEES.,477843,saudi aramco's liquefied petroleum gas (lpg) e...,1997-03-31,C31,477843newsML,saudi aramco liquefied petroleum gas lpg expor...,0
48341,Egypt offers 91-day T-bills worth 600 mln pounds.,477852,the egyptian treasury offered 91-day treasury ...,1997-03-31,M13,477852newsML,egyptian treasury offered treasury bill worth ...,0
48342,Lebanese markets and financial markets closed.,477853,financial markets and exchanges in lebanon wer...,1997-03-31,M11,477853newsML,financial market exchange lebanon closed monda...,0
48350,Greek 1M ATHIBOR rose to 10.90 from 10.72pct.,477861,the athens interbank offered rate (athibor) fo...,1997-03-31,M12,477861newsML,athens interbank offered rate athibor one mont...,0
48351,Greek 1M ATHIBOR edges up to 10.72 from 10.72pct.,477862,the athens interbank offered rate (athibor) fo...,1997-03-31,M12,477862newsML,athens interbank offered rate athibor one mont...,0
48364,India retains import curbs on consumer electro...,477875,"india's commerce ministry, said on monday that...",1997-03-31,E512,477875newsML,india commerce ministry said monday export pro...,0

In [34]:
for i in range(0,5):
    datasets[i].to_csv("C:/Users/raksh/Desktop/assignment/bigdata project/new_datasets/"+str(i)+".csv")

In [51]:
from sklearn.externals import joblib
X=[]
def cluster(data, num, file):
    matrix= tfidfconverter.fit_transform(data["processed_text"])
    X.append(matrix)
    joblib.dump(matrix,'C:/Users/raksh/Desktop/assignment/bigdata project/models/tfidf'+file+'.pkl')
    km = KMeans(n_clusters=num)
    km.fit(matrix)
    joblib.dump(km,'C:/Users/raksh/Desktop/assignment/bigdata project/models/model'+file+'.pkl')
    clusters = km.labels_.tolist()
    data['new_cluster']=clusters
    data.to_csv("C:/Users/raksh/Desktop/assignment/bigdata project/new_datasets/"+str(file)+".csv")
    return data

In [52]:
#cluster(datasets[0],len(datasets[0]['topics'].unique()), str(1))
for i in range(0,5):
    cluster(datasets[i], len(datasets[i]['topics'].unique()), str(i))

In [59]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
accuracys=[]
def models(i):
    X_train, X_test, y_train, y_test = train_test_split(X[i], datasets[i]['topics'], test_size=0.33, random_state=42)
    clf= MultinomialNB().fit(X_train, y_train)
    y_pred=clf.predict(X_test)
    accuracy={
        "accuracy": round(accuracy_score(y_test, y_pred)*100,2),
        "pscore": round(precision_score(y_test, y_pred, average='macro')*100,2),
        "rscore":round(recall_score(y_test, y_pred, average='macro')*100,2),
        "f1score":round(f1_score(y_test, y_pred, average='macro')*100,2)
        }
    accuracys.append(accuracy)

In [60]:
for i in range(0,5):
    models(i)

c:\users\raksh\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
c:\users\raksh\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
c:\users\raksh\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
c:\users\raksh\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
c:\users\raksh\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
c:\users\raksh\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
c:\users\raksh\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
c:\users\raksh\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
c:\users\raksh\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
c:\users\raksh\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [62]:
accuracys

[{'accuracy': 76.32, 'pscore': 33.98, 'rscore': 26.66, 'f1score': 27.43},
 {'accuracy': 99.05, 'pscore': 12.38, 'rscore': 12.5, 'f1score': 12.44},
 {'accuracy': 65.38, 'pscore': 28.42, 'rscore': 16.05, 'f1score': 17.82},
 {'accuracy': 60.12, 'pscore': 24.74, 'rscore': 14.16, 'f1score': 15.68},
 {'accuracy': 73.56, 'pscore': 15.39, 'rscore': 9.34, 'f1score': 10.08}]

In [76]:
from sklearn.svm import SVC
acc1=[]
def svm(i):
    X_train, X_test, y_train, y_test = train_test_split(X[i], datasets[i]['topics'], test_size=0.33, random_state=42)
    clf= SVC(gamma='scale', decision_function_shape='ovo').fit(X_train, y_train)
    y_pred=clf.predict(X_test)
    accuracy={
        "accuracy": round(accuracy_score(y_test, y_pred)*100,2),
        "pscore": round(precision_score(y_test, y_pred, average='macro')*100,2),
        "rscore":round(recall_score(y_test, y_pred, average='macro')*100,2),
        "f1score":round(f1_score(y_test, y_pred, average='macro')*100,2)
        }
    acc1.append(accuracy)

In [77]:
for i in range(0,5):
    svm(i)

c:\users\raksh\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
c:\users\raksh\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)

In [78]:
acc1

[{'accuracy': 82.96, 'pscore': 50.65, 'rscore': 40.14, 'f1score': 42.97},
 {'accuracy': 99.15, 'pscore': 24.89, 'rscore': 25.0, 'f1score': 24.95},
 {'accuracy': 76.94, 'pscore': 38.7, 'rscore': 30.39, 'f1score': 32.47},
 {'accuracy': 68.93, 'pscore': 43.08, 'rscore': 26.9, 'f1score': 30.81},
 {'accuracy': 78.64, 'pscore': 27.8, 'rscore': 15.12, 'f1score': 17.51}]